// <auto-generated />
using System;
using IWeddySupport.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IWeddySupport.Migrations
{
    [DbContext(typeof(IWeddySupportDbContext))]
    partial class IWeddySupportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("IWeddySupport.Model.Address", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("IWeddySupport.Model.EducationalQualification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DivisionOrDepartment")
                        .HasColumnType("longtext");

                    b.Property<int?>("GraduationYear")
                        .HasColumnType("int");

                    b.Property<string>("HighestEducationLevel")
                        .HasColumnType("longtext");

                    b.Property<string>("InstituteName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("ResultOrGrade")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("EducationalQualifications");
                });

            modelBuilder.Entity("IWeddySupport.Model.PartnerExpectation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DesiredCharacteristics")
                        .HasColumnType("longtext");

                    b.Property<string>("EducationalQualification")
                        .HasColumnType("longtext");

                    b.Property<string>("FinancialStatus")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<int?>("MaxAge")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MaxHeight")
                        .HasColumnType("int");

                    b.Property<int?>("MinAge")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("MinHeight")
                        .HasColumnType("int");

                    b.Property<string>("PreferredDistricts")
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredProfessions")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SkinTone")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("PartnerExpectations");
                });

            modelBuilder.Entity("IWeddySupport.Model.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BloodGroup")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("CanReciteQuranProperly")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("CompanyOrInstituteName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Declaration")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyEconomicsCondition")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FamilyReligiousEnvironment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FatherOccupationDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("HasMentalOrPhysicalIllness")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Height")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFatherAlive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsMotherAlive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MaritalStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MotherOccupationDetails")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NumberOfBrothers")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfSisters")
                        .HasColumnType("int");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PrayerHabit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Religion")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("SkinTone")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Weight")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("YearlySalary")
                        .HasColumnType("int");

                    b.Property<bool>("isPublic")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("IWeddySupport.Model.ProfilePhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileId")
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ProfilePhotos");
                });

            modelBuilder.Entity("IWeddySupport.Model.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProfileId")
                        .HasColumnType("longtext");

                    b.Property<string>("Relationship")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("IWeddySupport.Model.UserRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ExpacterProfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ExpacterUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Remarks")
                        .HasColumnType("longtext");

                    b.Property<string>("RequesterProfileId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RequesterUserId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedBy")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("UserRequestAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("UserRequestRejected")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("UserRequests");
                });

            modelBuilder.Entity("IWeddySupport.Model.Address", b =>
                {
                    b.OwnsOne("IWeddySupport.Model.AddressDetail", "CurrentAddress", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Thana")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("localAddress")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.OwnsOne("IWeddySupport.Model.AddressDetail", "PermanentAddress", b1 =>
                        {
                            b1.Property<Guid>("AddressId")
                                .HasColumnType("char(36)");

                            b1.Property<string>("District")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("Thana")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.Property<string>("localAddress")
                                .IsRequired()
                                .HasColumnType("longtext");

                            b1.HasKey("AddressId");

                            b1.ToTable("Addresses");

                            b1.WithOwner()
                                .HasForeignKey("AddressId");
                        });

                    b.Navigation("CurrentAddress")
                        .IsRequired();

                    b.Navigation("PermanentAddress")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
